### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by crb912** [neal1991/image-host#5]
The extension couldn't work on Chrome of Ubuntu 18.04 OS.
Since the upload interface wouldn't sticky, it will close automatically and unexpectedly when I drag and drop or choose my images via your user interface.

**Comment by madneal** [comment]
Is it possible to use a gif to describle this problem? Thanks.

**Comment by crb912** [comment]
GIF: http://opmuxsgc5.bkt.clouddn.com/Jul-25-2018-7niu-bug-report.gif

![bug-reproduce](http://opmuxsgc5.bkt.clouddn.com/Jul-25-2018-7niu-bug-report.gif)

**Comment by mzz2017** [comment]
#7 this new PR has fixed this bug
