### ISSUE TITLE
上传失败: 请检查AK/SK等配置正确，然后重新开启本窗口

### ISSUE THREAD

**Issue by duola8789** [neal1991/image-host#8]
上传失败: 请检查AK/SK等配置正确，然后重新开启本窗口

AK/SK等配置是正确的。

检测网络请求，发出了https://upload.qbox.me/的Post请求，返回了400

`error: "incorrect region, please use up-z0.qiniup.com`

**Comment by mzz2017** [comment]
最近比较忙，期待PR

**Comment by duola8789** [comment]
> 最近比较忙，期待PR

提交了一个[PR](https://github.com/neal1991/image-host/pull/9)，望审阅。

**Comment by mzz2017** [comment]
@neal1991 可以更新插件了

**Comment by madneal** [comment]
@mzz2017 以后会通过CI持续发布插件，记得修改版本号，不用@我了 😅
